### ISSUE TITLE
need .catch() in somewhere

### ISSUE THREAD

**Issue by kitsystemyou** [kitsystemyou/discordBot#19]
On glitch, these error occured (but not in local).
```
(node:173) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined

at Speech.msg (

:49)

at Parser.<anonymous> (

:25)

    at Parser.emit (events.js:196:13)

    at Parser.receive (/rbd/pnpm-volume/2342f98c-2114-4091-86cf-62a14b5bea5c/node_modules/twitter/lib/parser.js:58:16)

    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/2342f98c-2114-4091-86cf-62a14b5bea5c/node_modules/twitter/lib/twitter.js:284:14)

    at IncomingMessage.emit (events.js:201:15)

    at addChunk (_stream_readable.js:290:12)

    at readableAddChunk (_stream_readable.js:271:11)

    at IncomingMessage.Readable.push (_stream_readable.js:226:10)

    at HTTPParser.parserOnBody (_http_common.js:129:22)

(node:173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
```

// Glitch continue to serve. 🙄

**Comment by kitsystemyou** [comment]
Resolved in #27 ... ?
